name: Run OpenAI Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install OpenAI
        run: pip install openai

      - name: Run Python
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python app.py
